### ISSUE TITLE
请问README.md这里面有大量的公式，我需要用什么阅读器打开呢？

### ISSUE THREAD

**Issue by izhangyize** [PKU-HunterWu/LDPC-Encoder-Decoder#1]

**Comment by PKU-HunterWu** [comment]
我是用typora软件写的，你可以用typora打开.md文件，公式应该就能正常显示了

**Comment by PKU-HunterWu** [comment]
可以用typ

在 2022-05-13 16:42:25，nikolaeasy ***@***.***> 写道：

**Comment by PKU-HunterWu** [comment]
你好，我是用typora软件写的readme.md文件，你可以用typora打开它，公式会正常显示。

在 2022-05-13 16:42:25，nikolaeasy ***@***.***> 写道：
